title:        SGNG
tagline:      "Blog with jekyll"
url:          http://sgng.github.io
author:
  name:       "sugeng tigefa"
  email:      "sugeng.tigefa@gmail.com"
markdown:     rdiscount
permalink:    /articles/:title
pygments:     true
paginate:     5
